-- Auto generated by WoWBench 3.0.3.a2 from "C:/Users/user/SkyDrive/Programming/WoW_Addons/DHUD/DHUD/legacy/deprecated_DHUD.xml" on 2013-06-13 17:02:46
local WOWB_XMLFILE="C:/Users/user/SkyDrive/Programming/WoW_Addons/DHUD/DHUD/legacy/deprecated_DHUD.xml";
local WOWB_XMLFILENOPATH="C:/Users/user/SkyDrive/Programming/WoW_Addons/DHUD/DHUD/legacy/deprecated_DHUD.xml";
local WOWB_TAG = { [0]={content=""} }
local WOWB_PARENTOBJECT = WOWB_RootFrame;
local xfpc = WOWB_XMLFileParserContext:New(WOWB_XMLFILE);

do -- <Ui ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=1
local WOWB_TAG = { [0]={  xmltag="Ui",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=1,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["xmlns"] ="http://www.blizzard.com/wow/ui/",
["xmlns:xsi"] ="http://www.w3.org/2001/XMLSchema-instance",
["xsi:schemaLocation"] ="http://www.blizzard.com/wow/ui/FrameXML/UI.xsd",
}};
WOWB_PARENT[0]["Ui"] = WOWB_TAG;
do -- <Frame ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=6
local WOWB_TAG = { [0]={  xmltag="Frame",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=6,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["name"] ="DHUD_EventFrame",
["parent"] ="UIParent",
}};
if(not WOWB_ISVIRTUAL) then
  local o = WOWB_ParseXML_FixObjectName(xfpc:Recurse(WOWB_TAG), WOWB_TAG, WOWB_LASTOBJNAME);
  if(not o) then
    bIgnored = true;
  else
    WOWB_TAG = o;
  end
end
local WOWB_LASTOBJNAME = WOWB_TAG[0].name;
if(not bIgnored) then tinsert(WOWB_PARENT[0], WOWB_TAG); end
WOWB_InheritType(WOWB_TAG, WBClass.Frame);
WOWB_TAG[0].parentobj = WOWB_PARENTOBJECT;
if(WOWB_PARENTOBJECT) then
  WOWB_PARENTOBJECT[0].children[WOWB_TAG] = true;
end
local WOWB_PARENTOBJECT = (not WOWB_ISVIRTUAL) and WOWB_TAG or nil;
if WOWB_TAG[0].inherits then
  WOWB_ParseXML_InheritObj(xfpc:Recurse(WOWB_TAG), WOWB_TAG, WOWB_TAG[0].inherits, WOWB_ISVIRTUAL);
end
WOWB_RunObjConstructors(WOWB_TAG, WBClass.Frame);

do -- <Scripts ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=7
local WOWB_TAG = { [0]={  xmltag="Scripts",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=7,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
}};
if(not WOWB_PARENT[0]["Scripts"]) then
  WOWB_PARENT[0]["Scripts"] = WOWB_TAG;
else
  WOWB_TAG = WOWB_PARENT[0]["Scripts"];
end
do -- <OnLoad ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=8
local WOWB_TAG = { [0]={  xmltag="OnLoad",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=8,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
}};
WOWB_PARENT[0]["OnLoad"] = WOWB_TAG;
WOWB_TAG[0].content = WOWB_TAG[0].content .. "\n\t\t\t\tDHUD:OnLoad();\n\t\t\t";
WOWB_ParseXML_CompileScriptNode(xfpc:Recurse(WOWB_TAG), WOWB_TAG);end -- OnLoad
do -- <OnEvent ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=11
local WOWB_TAG = { [0]={  xmltag="OnEvent",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=11,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
}};
WOWB_PARENT[0]["OnEvent"] = WOWB_TAG;
WOWB_TAG[0].content = WOWB_TAG[0].content .. "\n\t\t\t\tlocal arg1, arg2, arg3 = ...;\n\t\t\t    DHUD:OnEvent(event, arg1, arg2, arg3);\n\t\t\t";
WOWB_ParseXML_CompileScriptNode(xfpc:Recurse(WOWB_TAG), WOWB_TAG);end -- OnEvent
do -- <OnUpdate ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=15
local WOWB_TAG = { [0]={  xmltag="OnUpdate",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=15,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
}};
WOWB_PARENT[0]["OnUpdate"] = WOWB_TAG;
WOWB_TAG[0].content = WOWB_TAG[0].content .. "\n                DHUD:OnUpdate(elapsed);\n\t\t\t";
WOWB_ParseXML_CompileScriptNode(xfpc:Recurse(WOWB_TAG), WOWB_TAG);end -- OnUpdate
end -- Scripts
end -- Frame
do -- <Frame ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=22
local WOWB_TAG = { [0]={  xmltag="Frame",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=22,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["name"] ="DHUD_Target_DropDown",
["inherits"] ="UIDropDownMenuTemplate",
["id"] =1,
["hidden"] ="false",
}};
if(not WOWB_ISVIRTUAL) then
  local o = WOWB_ParseXML_FixObjectName(xfpc:Recurse(WOWB_TAG), WOWB_TAG, WOWB_LASTOBJNAME);
  if(not o) then
    bIgnored = true;
  else
    WOWB_TAG = o;
  end
end
local WOWB_LASTOBJNAME = WOWB_TAG[0].name;
if(not bIgnored) then tinsert(WOWB_PARENT[0], WOWB_TAG); end
WOWB_InheritType(WOWB_TAG, WBClass.Frame);
WOWB_TAG[0].parentobj = WOWB_PARENTOBJECT;
if(WOWB_PARENTOBJECT) then
  WOWB_PARENTOBJECT[0].children[WOWB_TAG] = true;
end
local WOWB_PARENTOBJECT = (not WOWB_ISVIRTUAL) and WOWB_TAG or nil;
if WOWB_TAG[0].inherits then
  WOWB_ParseXML_InheritObj(xfpc:Recurse(WOWB_TAG), WOWB_TAG, WOWB_TAG[0].inherits, WOWB_ISVIRTUAL);
end
WOWB_RunObjConstructors(WOWB_TAG, WBClass.Frame);

do -- <Size ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=23
local WOWB_TAG = { [0]={  xmltag="Size",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=23,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
}};
WOWB_PARENT[0]["Size"] = WOWB_TAG;
do -- <AbsDimension ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=24
local WOWB_TAG = { [0]={  xmltag="AbsDimension",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=24,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["x"] =160,
["y"] =160,
}};
WOWB_PARENT[0]["AbsDimension"] = WOWB_TAG;
end -- AbsDimension
end -- Size
do -- <Anchors ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=26
local WOWB_TAG = { [0]={  xmltag="Anchors",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=26,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
}};
if(not WOWB_PARENT[0]["Anchors"]) then
  WOWB_PARENT[0]["Anchors"] = WOWB_TAG;
else
  WOWB_TAG = WOWB_PARENT[0]["Anchors"];
end
do -- <Anchor ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=27
local WOWB_TAG = { [0]={  xmltag="Anchor",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=27,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["point"] ="TOP",
}};
tinsert(WOWB_PARENT[0], WOWB_TAG);
do -- <Offset ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=28
local WOWB_TAG = { [0]={  xmltag="Offset",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=28,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
}};
WOWB_PARENT[0]["Offset"] = WOWB_TAG;
do -- <AbsDimension ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=29
local WOWB_TAG = { [0]={  xmltag="AbsDimension",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=29,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["x"] =0,
["y"] =0,
}};
WOWB_PARENT[0]["AbsDimension"] = WOWB_TAG;
end -- AbsDimension
WOWB_ParseXML_CompileScriptNode(xfpc:Recurse(WOWB_TAG), WOWB_TAG);end -- Offset
end -- Anchor
end -- Anchors
do -- <Scripts ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=33
local WOWB_TAG = { [0]={  xmltag="Scripts",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=33,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
}};
if(not WOWB_PARENT[0]["Scripts"]) then
  WOWB_PARENT[0]["Scripts"] = WOWB_TAG;
else
  WOWB_TAG = WOWB_PARENT[0]["Scripts"];
end
do -- <OnLoad ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=34
local WOWB_TAG = { [0]={  xmltag="OnLoad",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=34,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
}};
WOWB_PARENT[0]["OnLoad"] = WOWB_TAG;
WOWB_TAG[0].content = WOWB_TAG[0].content .. "\n                UIDropDownMenu_Initialize(self, DHUD_Target_DropDown_Initialize, \"MENU\");\n            ";
WOWB_ParseXML_CompileScriptNode(xfpc:Recurse(WOWB_TAG), WOWB_TAG);end -- OnLoad
end -- Scripts
end -- Frame
do -- <Frame ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=41
local WOWB_TAG = { [0]={  xmltag="Frame",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=41,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["name"] ="DHUD_Player_DropDown",
["inherits"] ="UIDropDownMenuTemplate",
["id"] =2,
["hidden"] ="false",
}};
if(not WOWB_ISVIRTUAL) then
  local o = WOWB_ParseXML_FixObjectName(xfpc:Recurse(WOWB_TAG), WOWB_TAG, WOWB_LASTOBJNAME);
  if(not o) then
    bIgnored = true;
  else
    WOWB_TAG = o;
  end
end
local WOWB_LASTOBJNAME = WOWB_TAG[0].name;
if(not bIgnored) then tinsert(WOWB_PARENT[0], WOWB_TAG); end
WOWB_InheritType(WOWB_TAG, WBClass.Frame);
WOWB_TAG[0].parentobj = WOWB_PARENTOBJECT;
if(WOWB_PARENTOBJECT) then
  WOWB_PARENTOBJECT[0].children[WOWB_TAG] = true;
end
local WOWB_PARENTOBJECT = (not WOWB_ISVIRTUAL) and WOWB_TAG or nil;
if WOWB_TAG[0].inherits then
  WOWB_ParseXML_InheritObj(xfpc:Recurse(WOWB_TAG), WOWB_TAG, WOWB_TAG[0].inherits, WOWB_ISVIRTUAL);
end
WOWB_RunObjConstructors(WOWB_TAG, WBClass.Frame);

do -- <Size ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=42
local WOWB_TAG = { [0]={  xmltag="Size",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=42,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
}};
WOWB_PARENT[0]["Size"] = WOWB_TAG;
do -- <AbsDimension ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=43
local WOWB_TAG = { [0]={  xmltag="AbsDimension",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=43,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["x"] =160,
["y"] =160,
}};
WOWB_PARENT[0]["AbsDimension"] = WOWB_TAG;
end -- AbsDimension
end -- Size
do -- <Anchors ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=45
local WOWB_TAG = { [0]={  xmltag="Anchors",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=45,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
}};
if(not WOWB_PARENT[0]["Anchors"]) then
  WOWB_PARENT[0]["Anchors"] = WOWB_TAG;
else
  WOWB_TAG = WOWB_PARENT[0]["Anchors"];
end
do -- <Anchor ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=46
local WOWB_TAG = { [0]={  xmltag="Anchor",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=46,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["point"] ="TOP",
}};
tinsert(WOWB_PARENT[0], WOWB_TAG);
do -- <Offset ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=47
local WOWB_TAG = { [0]={  xmltag="Offset",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=47,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
}};
WOWB_PARENT[0]["Offset"] = WOWB_TAG;
do -- <AbsDimension ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=48
local WOWB_TAG = { [0]={  xmltag="AbsDimension",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=48,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["x"] =0,
["y"] =0,
}};
WOWB_PARENT[0]["AbsDimension"] = WOWB_TAG;
end -- AbsDimension
WOWB_ParseXML_CompileScriptNode(xfpc:Recurse(WOWB_TAG), WOWB_TAG);end -- Offset
end -- Anchor
end -- Anchors
do -- <Scripts ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=52
local WOWB_TAG = { [0]={  xmltag="Scripts",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=52,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
}};
if(not WOWB_PARENT[0]["Scripts"]) then
  WOWB_PARENT[0]["Scripts"] = WOWB_TAG;
else
  WOWB_TAG = WOWB_PARENT[0]["Scripts"];
end
do -- <OnLoad ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=53
local WOWB_TAG = { [0]={  xmltag="OnLoad",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=53,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
}};
WOWB_PARENT[0]["OnLoad"] = WOWB_TAG;
WOWB_TAG[0].content = WOWB_TAG[0].content .. "\n                UIDropDownMenu_Initialize(self, DHUD_Player_DropDown_Initialize, \"MENU\");\n            ";
WOWB_ParseXML_CompileScriptNode(xfpc:Recurse(WOWB_TAG), WOWB_TAG);end -- OnLoad
end -- Scripts
end -- Frame
end -- Ui
if(not WOWB_TAG[0][WOWB_ROOTXMLTAG]) then xfpc:error("No <"..WOWB_ROOTXMLTAG.."> tag?"); end
WOWB_ParseXML_QueueScripts(WOWB_TAG[0][WOWB_ROOTXMLTAG]);

xfpc:Return();
